#define BAUD_RATE 115200
#define MAX_ACCELEROMETER_READING 2.0
#define WIFI_CONNECT_RETRY_LIMIT 5
#define COOLDOWN_MS 60000
#define ACCELEROMETER_ZERO_OBSERVATIONS 1040
#define ACCELEROMETER_THRESHOLD 0.020
#define ACCELEROMETER_MAX_MAGNITUDE_SAMPLE_SIZE 104 // 1s